//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `App.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package Demo;

public interface SubscriberPrx extends com.zeroc.Ice.ObjectPrx
{
    default int[] calculatePerfectNum(int minN, int maxN)
    {
        return calculatePerfectNum(minN, maxN, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default int[] calculatePerfectNum(int minN, int maxN, java.util.Map<String, String> context)
    {
        return _iceI_calculatePerfectNumAsync(minN, maxN, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<int[]> calculatePerfectNumAsync(int minN, int maxN)
    {
        return _iceI_calculatePerfectNumAsync(minN, maxN, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<int[]> calculatePerfectNumAsync(int minN, int maxN, java.util.Map<String, String> context)
    {
        return _iceI_calculatePerfectNumAsync(minN, maxN, context, false);
    }

    /**
     * @hidden
     * @param iceP_minN -
     * @param iceP_maxN -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<int[]> _iceI_calculatePerfectNumAsync(int iceP_minN, int iceP_maxN, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<int[]> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "calculatePerfectNum", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeInt(iceP_minN);
                     ostr.writeInt(iceP_maxN);
                 }, istr -> {
                     int[] ret;
                     ret = istr.readIntSeq();
                     return ret;
                 });
        return f;
    }

    default void onUpdate(String msg)
    {
        onUpdate(msg, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void onUpdate(String msg, java.util.Map<String, String> context)
    {
        _iceI_onUpdateAsync(msg, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> onUpdateAsync(String msg)
    {
        return _iceI_onUpdateAsync(msg, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> onUpdateAsync(String msg, java.util.Map<String, String> context)
    {
        return _iceI_onUpdateAsync(msg, context, false);
    }

    /**
     * @hidden
     * @param iceP_msg -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_onUpdateAsync(String iceP_msg, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "onUpdate", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_msg);
                 }, null);
        return f;
    }

    default void requestRange(int start, int end)
    {
        requestRange(start, end, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void requestRange(int start, int end, java.util.Map<String, String> context)
    {
        _iceI_requestRangeAsync(start, end, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> requestRangeAsync(int start, int end)
    {
        return _iceI_requestRangeAsync(start, end, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> requestRangeAsync(int start, int end, java.util.Map<String, String> context)
    {
        return _iceI_requestRangeAsync(start, end, context, false);
    }

    /**
     * @hidden
     * @param iceP_start -
     * @param iceP_end -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_requestRangeAsync(int iceP_start, int iceP_end, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "requestRange", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeInt(iceP_start);
                     ostr.writeInt(iceP_end);
                 }, null);
        return f;
    }

    default void displayResults(int[] numbers)
    {
        displayResults(numbers, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void displayResults(int[] numbers, java.util.Map<String, String> context)
    {
        _iceI_displayResultsAsync(numbers, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> displayResultsAsync(int[] numbers)
    {
        return _iceI_displayResultsAsync(numbers, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> displayResultsAsync(int[] numbers, java.util.Map<String, String> context)
    {
        return _iceI_displayResultsAsync(numbers, context, false);
    }

    /**
     * @hidden
     * @param iceP_numbers -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_displayResultsAsync(int[] iceP_numbers, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "displayResults", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeIntSeq(iceP_numbers);
                 }, null);
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SubscriberPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), SubscriberPrx.class, _SubscriberPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SubscriberPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), SubscriberPrx.class, _SubscriberPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SubscriberPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), SubscriberPrx.class, _SubscriberPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static SubscriberPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), SubscriberPrx.class, _SubscriberPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static SubscriberPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, SubscriberPrx.class, _SubscriberPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static SubscriberPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, SubscriberPrx.class, _SubscriberPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default SubscriberPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (SubscriberPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default SubscriberPrx ice_adapterId(String newAdapterId)
    {
        return (SubscriberPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default SubscriberPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (SubscriberPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default SubscriberPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (SubscriberPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default SubscriberPrx ice_invocationTimeout(int newTimeout)
    {
        return (SubscriberPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default SubscriberPrx ice_connectionCached(boolean newCache)
    {
        return (SubscriberPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default SubscriberPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (SubscriberPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SubscriberPrx ice_secure(boolean b)
    {
        return (SubscriberPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default SubscriberPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (SubscriberPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default SubscriberPrx ice_preferSecure(boolean b)
    {
        return (SubscriberPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default SubscriberPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (SubscriberPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default SubscriberPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (SubscriberPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default SubscriberPrx ice_collocationOptimized(boolean b)
    {
        return (SubscriberPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default SubscriberPrx ice_twoway()
    {
        return (SubscriberPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default SubscriberPrx ice_oneway()
    {
        return (SubscriberPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default SubscriberPrx ice_batchOneway()
    {
        return (SubscriberPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default SubscriberPrx ice_datagram()
    {
        return (SubscriberPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default SubscriberPrx ice_batchDatagram()
    {
        return (SubscriberPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default SubscriberPrx ice_compress(boolean co)
    {
        return (SubscriberPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default SubscriberPrx ice_timeout(int t)
    {
        return (SubscriberPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default SubscriberPrx ice_connectionId(String connectionId)
    {
        return (SubscriberPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default SubscriberPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (SubscriberPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::Demo::Subscriber";
    }
}
